use edit_distance;
use regex::Regex;
use std::hash::{Hash, Hasher};

#[derive(Debug, Hash, Clone, PartialEq, Eq)]
pub enum ArtifactStatKey {
    HealingBonus,
    CriticalDamage,
    Critical,
    Atk,
    AtkPercentage,
    ElementalMastery,
    Recharge,
    HpPercentage,
    Hp,
    DefPercentage,
    Def,
    ElectroBonus,
    PyroBonus,
    HydroBonus,
    CryoBonus,
    AnemoBonus,
    GeoBonus,
    PhysicalBonus,
}

#[derive(Debug, Hash, Clone, PartialEq, Eq)]
pub enum ArtifactSlotKey {
    Flower,
    Plume,
    Sands,
    Goblet,
    Circlet,
}

#[derive(Debug, Hash, Clone, PartialEq, Eq)]
pub enum ArtifactSetKey {
    ArchaicPetra,
    HeartOfDepth,
    BlizzardStrayer,
    RetracingBolide,
    NoblesseOblige,
    GladiatorsFinale,
    MaidenBeloved,
    ViridescentVenerer,
    Lavawalker,
    CrimsonWitchOfFlames,
    Thundersoother,
    ThunderingFury,
    BloodstainedChivalry,
    WanderersTroupe,
    Scholar,
    Gambler,
    TinyMiracle,
    MartialArtist,
    BraveHeart,
    ResolutionOfSojourner,
    DefenderWill,
    Berserker,
    Instructor,
    Exile,
    Adventurer,
    LuckyDog,
    TravelingDoctor,
    PrayersForWisdom,
    PrayersToSpringtime,
    PrayersForIllumination,
    PrayersForDestiny,
    PaleFlame,
    TenacityOfTheMillelith,
    EmblemOfSeveredFate,
    ShimenawasReminiscence,
    HuskOfOpulentDreams,
    OceanHuedClam,
}

#[derive(Debug, Hash, Clone, PartialEq, Eq)]
pub enum CharacterKey {
    Albedo,
    Aloy,
    Amber,
    AratakiItto,
    Barbara,
    Beidou,
    Bennett,
    Chongyun,
    Diluc,
    Diona,
    Eula,
    Fischl,
    Ganyu,
    Gorou,
    HuTao,
    Jean,
    KaedeharaKazuha,
    Kaeya,
    KamisatoAyaka,
    Keqing,
    Klee,
    KujouSara,
    Lisa,
    Mona,
    Ningguang,
    Noelle,
    Qiqi,
    RaidenShogun,
    Razor,
    Rosaria,
    SangonomiyaKokomi,
    Sayu,
    Sucrose,
    Tartaglia,
    Thoma,
    Traveler,
    Venti,
    Xiangling,
    Xiao,
    Xingqiu,
    Xinyan,
    Yanfei,
    Yoimiya,
    Zhongli,
}

#[derive(Debug, Clone)]
pub struct ArtifactStat {
    pub key: ArtifactStatKey,
    pub value: f64,
}

#[derive(Debug, Hash, Clone, PartialEq, Eq)]
pub struct InternalArtifact {
    pub set_key: ArtifactSetKey,
    pub slot_key: ArtifactSlotKey,
    pub rarity: u32,
    pub level: u32,
    pub lock: bool,
    pub location: Option<CharacterKey>,
    pub main_stat: ArtifactStat,
    pub sub_stat_1: Option<ArtifactStat>,
    pub sub_stat_2: Option<ArtifactStat>,
    pub sub_stat_3: Option<ArtifactStat>,
    pub sub_stat_4: Option<ArtifactStat>,
}

impl Hash for ArtifactStat {
    fn hash<H: Hasher>(&self, state: &mut H) {
        self.key.hash(state);
        let v = (self.value * 1000.0) as i32;
        v.hash(state);
    }
}

impl PartialEq for ArtifactStat {
    fn eq(&self, other: &Self) -> bool {
        if self.key != other.key {
            return false;
        }

        let v1 = (self.value * 1000.0) as i32;
        let v2 = (other.value * 1000.0) as i32;

        v1 == v2
    }
}

impl Eq for ArtifactStat {}

impl ArtifactStatKey {
    pub fn from_zh_cn(name: &str, is_percentage: bool) -> Option<ArtifactStatKey> {
        match name {
            "治疗加成" => Some(ArtifactStatKey::HealingBonus),
            "暴击伤害" => Some(ArtifactStatKey::CriticalDamage),
            "暴击率" => Some(ArtifactStatKey::Critical),
            "攻击力" => {
                if is_percentage {
                    Some(ArtifactStatKey::AtkPercentage)
                } else {
                    Some(ArtifactStatKey::Atk)
                }
            }
            "元素精通" => Some(ArtifactStatKey::ElementalMastery),
            "元素充能效率" => Some(ArtifactStatKey::Recharge),
            "生命值" => {
                if is_percentage {
                    Some(ArtifactStatKey::HpPercentage)
                } else {
                    Some(ArtifactStatKey::Hp)
                }
            }
            "防御力" => {
                if is_percentage {
                    Some(ArtifactStatKey::DefPercentage)
                } else {
                    Some(ArtifactStatKey::Def)
                }
            }
            "雷元素伤害加成" => Some(ArtifactStatKey::ElectroBonus),
            "火元素伤害加成" => Some(ArtifactStatKey::PyroBonus),
            "水元素伤害加成" => Some(ArtifactStatKey::HydroBonus),
            "冰元素伤害加成" => Some(ArtifactStatKey::CryoBonus),
            "风元素伤害加成" => Some(ArtifactStatKey::AnemoBonus),
            "岩元素伤害加成" => Some(ArtifactStatKey::GeoBonus),
            "物理伤害加成" => Some(ArtifactStatKey::PhysicalBonus),
            _ => None,
        }
    }
}

impl ArtifactStat {
    // e.g "生命值+4,123", "暴击率+10%"
    pub fn from_zh_cn_raw(s: &str) -> Option<ArtifactStat> {
        let temp: Vec<&str> = s.split("+").collect();
        if temp.len() != 2 {
            return None;
        }

        let is_percentage = temp[1].contains("%");
        let stat_key = match ArtifactStatKey::from_zh_cn(temp[0], is_percentage) {
            Some(v) => v,
            None => return None,
        };

        let re = Regex::new("[%,]").unwrap();
        let value = re.replace_all(temp[1], "").parse::<f64>().unwrap();
        // if is_percentage {
        //     value /= 100.0;
        // }

        Some(ArtifactStat {
            key: stat_key,
            value,
        })
    }
}

pub fn get_real_artifact_name_chs(raw: &str) -> Option<String> {
    let all_artifact_chs = [
        "磐陀裂生之花",
        "嵯峨群峰之翼",
        "星罗圭壁之晷",
        "星罗圭璧之晷",
        "巉岩琢塑之樽",
        "不动玄石之相",
        "历经风雪的思念",
        "摧冰而行的执望",
        "冰雪故园的终期",
        "遍结寒霜的傲骨",
        "破冰踏雪的回音",
        "染血的铁之心",
        "染血的黑之羽",
        "骑士染血之时",
        "染血骑士之杯",
        "染血的铁假面",
        "魔女的炎之花",
        "魔女常燃之羽",
        "魔女破灭之时",
        "魔女的心之火",
        "焦灼的魔女帽",
        "角斗士的留恋",
        "角斗士的归宿",
        "角斗士的希冀",
        "角斗士的酣醉",
        "角斗士的凯旋",
        "饰金胸花",
        "追忆之风",
        "坚铜罗盘",
        "沉波之盏",
        "酒渍船帽",
        "渡火者的决绝",
        "渡火者的解脱",
        "渡火者的煎熬",
        "渡火者的醒悟",
        "渡火者的智慧",
        "远方的少女之心",
        "少女飘摇的思念",
        "少女苦短的良辰",
        "少女片刻的闲暇",
        "少女易逝的芳颜",
        "宗室之花",
        "宗室之翎",
        "宗室时计",
        "宗室银瓮",
        "宗室面具",
        "夏祭之花",
        "夏祭终末",
        "夏祭之刻",
        "夏祭水玉",
        "夏祭之面",
        "平雷之心",
        "平雷之羽",
        "平雷之刻",
        "平雷之器",
        "平雷之冠",
        "雷鸟的怜悯",
        "雷灾的孑遗",
        "雷霆的时计",
        "降雷的凶兆",
        "唤雷的头冠",
        "野花记忆的绿野",
        "猎人青翠的箭羽",
        "翠绿猎人的笃定",
        "翠绿猎人的容器",
        "翠绿的猎人之冠",
        "乐团的晨光",
        "琴师的箭羽",
        "终幕的时计",
        "终末的时计",
        "吟游者之壶",
        "指挥的礼帽",
        "战狂的蔷薇",
        "战狂的翎羽",
        "战狂的时计",
        "战狂的骨杯",
        "战狂的鬼面",
        "勇士的勋章",
        "勇士的期许",
        "勇士的坚毅",
        "勇士的壮行",
        "勇士的冠冕",
        "守护之花",
        "守护徽印",
        "守护座钟",
        "守护之皿",
        "守护束带",
        "流放者之花",
        "流放者之羽",
        "流放者怀表",
        "流放者之杯",
        "流放者头冠",
        "赌徒的胸花",
        "赌徒的羽饰",
        "赌徒的怀表",
        "赌徒的骰盅",
        "赌徒的耳环",
        "教官的胸花",
        "教官的羽饰",
        "教官的怀表",
        "教官的茶杯",
        "教官的帽子",
        "武人的红花",
        "武人的羽饰",
        "武人的水漏",
        "武人的酒杯",
        "武人的头巾",
        "祭水礼冠",
        "祭火礼冠",
        "祭雷礼冠",
        "祭冰礼冠",
        "故人之心",
        "归乡之羽",
        "逐光之石",
        "异国之盏",
        "感别之冠",
        "学士的书签",
        "学士的羽笔",
        "学士的时钟",
        "学士的墨杯",
        "学士的镜片",
        "奇迹之花",
        "奇迹之羽",
        "奇迹之沙",
        "奇迹之杯",
        "奇迹耳坠",
        "冒险家之花",
        "冒险家尾羽",
        "冒险家怀表",
        "冒险家金杯",
        "冒险家头带",
        "幸运儿绿花",
        "幸运儿鹰羽",
        "幸运儿沙漏",
        "幸运儿之杯",
        "幸运儿银冠",
        "游医的银莲",
        "游医的枭羽",
        "游医的怀钟",
        "游医的药壶",
        "游医的方巾",
        "勋绩之花",
        "昭武翎羽",
        "金铜时晷",
        "盟誓金爵",
        "将帅兜鍪",
        "无垢之花",
        "贤医之羽",
        "停摆之刻",
        "超越之盏",
        "嗤笑之面",
        "明威之镡",
        "切落之羽",
        "雷云之笼",
        "绯花之壶",
        "华饰之兜",
        "羁缠之花",
        "思忆之矢",
        "朝露之时",
        "祈望之心",
        "无常之面",
        "荣花之期",
        "华馆之羽",
        "众生之谣",
        "梦醒之瓢",
        "形骸之笠",
        "海染之花",
        "渊宫之羽",
        "离别之贝",
        "真珠之笼",
        "海祇之冠",
    ];

    let mut min_index = 0;
    let mut min_dis = edit_distance::edit_distance(raw, all_artifact_chs[0]);
    let mut same_flag = false;
    for (i, &val) in all_artifact_chs.iter().enumerate().skip(1) {
        let dis = edit_distance::edit_distance(val, raw);
        if dis < min_dis {
            min_dis = dis;
            min_index = i;
            same_flag = false;
        } else if dis == min_dis {
            same_flag = true;
        }
    }

    if same_flag {
        None
    } else {
        Some(String::from(all_artifact_chs[min_index]))
    }
}

impl ArtifactSetKey {
    pub fn from_zh_cn(s: &str) -> Option<ArtifactSetKey> {
        // let s = match get_real_artifact_name_chs(s) {
        //     Some(v) => v,
        //     None => return None,
        // };
        // println!("name: {}", s);
        match s {
            "磐陀裂生之花" => Some(ArtifactSetKey::ArchaicPetra),
            "嵯峨群峰之翼" => Some(ArtifactSetKey::ArchaicPetra),
            "星罗圭壁之晷" => Some(ArtifactSetKey::ArchaicPetra),
            // "壁" is different
            "星罗圭璧之晷" => Some(ArtifactSetKey::ArchaicPetra),
            "巉岩琢塑之樽" => Some(ArtifactSetKey::ArchaicPetra),
            "不动玄石之相" => Some(ArtifactSetKey::ArchaicPetra),
            "历经风雪的思念" => Some(ArtifactSetKey::BlizzardStrayer),
            "摧冰而行的执望" => Some(ArtifactSetKey::BlizzardStrayer),
            "冰雪故园的终期" => Some(ArtifactSetKey::BlizzardStrayer),
            "遍结寒霜的傲骨" => Some(ArtifactSetKey::BlizzardStrayer),
            "破冰踏雪的回音" => Some(ArtifactSetKey::BlizzardStrayer),
            "染血的铁之心" => Some(ArtifactSetKey::BloodstainedChivalry),
            "染血的黑之羽" => Some(ArtifactSetKey::BloodstainedChivalry),
            "骑士染血之时" => Some(ArtifactSetKey::BloodstainedChivalry),
            "染血骑士之杯" => Some(ArtifactSetKey::BloodstainedChivalry),
            "染血的铁假面" => Some(ArtifactSetKey::BloodstainedChivalry),
            "魔女的炎之花" => Some(ArtifactSetKey::CrimsonWitchOfFlames),
            "魔女常燃之羽" => Some(ArtifactSetKey::CrimsonWitchOfFlames),
            "魔女破灭之时" => Some(ArtifactSetKey::CrimsonWitchOfFlames),
            "魔女的心之火" => Some(ArtifactSetKey::CrimsonWitchOfFlames),
            "焦灼的魔女帽" => Some(ArtifactSetKey::CrimsonWitchOfFlames),
            "角斗士的留恋" => Some(ArtifactSetKey::GladiatorsFinale),
            "角斗士的归宿" => Some(ArtifactSetKey::GladiatorsFinale),
            "角斗士的希冀" => Some(ArtifactSetKey::GladiatorsFinale),
            "角斗士的酣醉" => Some(ArtifactSetKey::GladiatorsFinale),
            "角斗士的凯旋" => Some(ArtifactSetKey::GladiatorsFinale),
            "饰金胸花" => Some(ArtifactSetKey::HeartOfDepth),
            "追忆之风" => Some(ArtifactSetKey::HeartOfDepth),
            "坚铜罗盘" => Some(ArtifactSetKey::HeartOfDepth),
            "沉波之盏" => Some(ArtifactSetKey::HeartOfDepth),
            "酒渍船帽" => Some(ArtifactSetKey::HeartOfDepth),
            "渡火者的决绝" => Some(ArtifactSetKey::Lavawalker),
            "渡火者的解脱" => Some(ArtifactSetKey::Lavawalker),
            "渡火者的煎熬" => Some(ArtifactSetKey::Lavawalker),
            "渡火者的醒悟" => Some(ArtifactSetKey::Lavawalker),
            "渡火者的智慧" => Some(ArtifactSetKey::Lavawalker),
            "远方的少女之心" => Some(ArtifactSetKey::MaidenBeloved),
            "少女飘摇的思念" => Some(ArtifactSetKey::MaidenBeloved),
            "少女苦短的良辰" => Some(ArtifactSetKey::MaidenBeloved),
            "少女片刻的闲暇" => Some(ArtifactSetKey::MaidenBeloved),
            "少女易逝的芳颜" => Some(ArtifactSetKey::MaidenBeloved),
            "宗室之花" => Some(ArtifactSetKey::NoblesseOblige),
            "宗室之翎" => Some(ArtifactSetKey::NoblesseOblige),
            "宗室时计" => Some(ArtifactSetKey::NoblesseOblige),
            "宗室银瓮" => Some(ArtifactSetKey::NoblesseOblige),
            "宗室面具" => Some(ArtifactSetKey::NoblesseOblige),
            "夏祭之花" => Some(ArtifactSetKey::RetracingBolide),
            "夏祭终末" => Some(ArtifactSetKey::RetracingBolide),
            "夏祭之刻" => Some(ArtifactSetKey::RetracingBolide),
            "夏祭水玉" => Some(ArtifactSetKey::RetracingBolide),
            "夏祭之面" => Some(ArtifactSetKey::RetracingBolide),
            "平雷之心" => Some(ArtifactSetKey::Thundersoother),
            "平雷之羽" => Some(ArtifactSetKey::Thundersoother),
            "平雷之刻" => Some(ArtifactSetKey::Thundersoother),
            "平雷之器" => Some(ArtifactSetKey::Thundersoother),
            "平雷之冠" => Some(ArtifactSetKey::Thundersoother),
            "雷鸟的怜悯" => Some(ArtifactSetKey::ThunderingFury),
            "雷灾的孑遗" => Some(ArtifactSetKey::ThunderingFury),
            "雷霆的时计" => Some(ArtifactSetKey::ThunderingFury),
            "降雷的凶兆" => Some(ArtifactSetKey::ThunderingFury),
            "唤雷的头冠" => Some(ArtifactSetKey::ThunderingFury),
            "野花记忆的绿野" => Some(ArtifactSetKey::ViridescentVenerer),
            "猎人青翠的箭羽" => Some(ArtifactSetKey::ViridescentVenerer),
            "翠绿猎人的笃定" => Some(ArtifactSetKey::ViridescentVenerer),
            "翠绿猎人的容器" => Some(ArtifactSetKey::ViridescentVenerer),
            "翠绿的猎人之冠" => Some(ArtifactSetKey::ViridescentVenerer),
            "乐团的晨光" => Some(ArtifactSetKey::WanderersTroupe),
            "琴师的箭羽" => Some(ArtifactSetKey::WanderersTroupe),
            "终幕的时计" => Some(ArtifactSetKey::WanderersTroupe),
            "终末的时计" => Some(ArtifactSetKey::WanderersTroupe),
            "吟游者之壶" => Some(ArtifactSetKey::WanderersTroupe),
            "指挥的礼帽" => Some(ArtifactSetKey::WanderersTroupe),
            "战狂的蔷薇" => Some(ArtifactSetKey::Berserker),
            "战狂的翎羽" => Some(ArtifactSetKey::Berserker),
            "战狂的时计" => Some(ArtifactSetKey::Berserker),
            "战狂的骨杯" => Some(ArtifactSetKey::Berserker),
            "战狂的鬼面" => Some(ArtifactSetKey::Berserker),
            "勇士的勋章" => Some(ArtifactSetKey::BraveHeart),
            "勇士的期许" => Some(ArtifactSetKey::BraveHeart),
            "勇士的坚毅" => Some(ArtifactSetKey::BraveHeart),
            "勇士的壮行" => Some(ArtifactSetKey::BraveHeart),
            "勇士的冠冕" => Some(ArtifactSetKey::BraveHeart),
            "守护之花" => Some(ArtifactSetKey::DefenderWill),
            "守护徽印" => Some(ArtifactSetKey::DefenderWill),
            "守护座钟" => Some(ArtifactSetKey::DefenderWill),
            "守护之皿" => Some(ArtifactSetKey::DefenderWill),
            "守护束带" => Some(ArtifactSetKey::DefenderWill),
            "流放者之花" => Some(ArtifactSetKey::Exile),
            "流放者之羽" => Some(ArtifactSetKey::Exile),
            "流放者怀表" => Some(ArtifactSetKey::Exile),
            "流放者之杯" => Some(ArtifactSetKey::Exile),
            "流放者头冠" => Some(ArtifactSetKey::Exile),
            "赌徒的胸花" => Some(ArtifactSetKey::Gambler),
            "赌徒的羽饰" => Some(ArtifactSetKey::Gambler),
            "赌徒的怀表" => Some(ArtifactSetKey::Gambler),
            "赌徒的骰盅" => Some(ArtifactSetKey::Gambler),
            "赌徒的耳环" => Some(ArtifactSetKey::Gambler),
            "教官的胸花" => Some(ArtifactSetKey::Instructor),
            "教官的羽饰" => Some(ArtifactSetKey::Instructor),
            "教官的怀表" => Some(ArtifactSetKey::Instructor),
            "教官的茶杯" => Some(ArtifactSetKey::Instructor),
            "教官的帽子" => Some(ArtifactSetKey::Instructor),
            "武人的红花" => Some(ArtifactSetKey::MartialArtist),
            "武人的羽饰" => Some(ArtifactSetKey::MartialArtist),
            "武人的水漏" => Some(ArtifactSetKey::MartialArtist),
            "武人的酒杯" => Some(ArtifactSetKey::MartialArtist),
            "武人的头巾" => Some(ArtifactSetKey::MartialArtist),
            "祭水礼冠" => Some(ArtifactSetKey::PrayersForDestiny),
            "祭火礼冠" => Some(ArtifactSetKey::PrayersForIllumination),
            "祭雷礼冠" => Some(ArtifactSetKey::PrayersForWisdom),
            "祭冰礼冠" => Some(ArtifactSetKey::PrayersToSpringtime),
            "故人之心" => Some(ArtifactSetKey::ResolutionOfSojourner),
            "归乡之羽" => Some(ArtifactSetKey::ResolutionOfSojourner),
            "逐光之石" => Some(ArtifactSetKey::ResolutionOfSojourner),
            "异国之盏" => Some(ArtifactSetKey::ResolutionOfSojourner),
            "感别之冠" => Some(ArtifactSetKey::ResolutionOfSojourner),
            "学士的书签" => Some(ArtifactSetKey::Scholar),
            "学士的羽笔" => Some(ArtifactSetKey::Scholar),
            "学士的时钟" => Some(ArtifactSetKey::Scholar),
            "学士的墨杯" => Some(ArtifactSetKey::Scholar),
            "学士的镜片" => Some(ArtifactSetKey::Scholar),
            "奇迹之花" => Some(ArtifactSetKey::TinyMiracle),
            "奇迹之羽" => Some(ArtifactSetKey::TinyMiracle),
            "奇迹之沙" => Some(ArtifactSetKey::TinyMiracle),
            "奇迹之杯" => Some(ArtifactSetKey::TinyMiracle),
            "奇迹耳坠" => Some(ArtifactSetKey::TinyMiracle),
            "冒险家之花" => Some(ArtifactSetKey::Adventurer),
            "冒险家尾羽" => Some(ArtifactSetKey::Adventurer),
            "冒险家怀表" => Some(ArtifactSetKey::Adventurer),
            "冒险家金杯" => Some(ArtifactSetKey::Adventurer),
            "冒险家头带" => Some(ArtifactSetKey::Adventurer),
            "幸运儿绿花" => Some(ArtifactSetKey::LuckyDog),
            "幸运儿鹰羽" => Some(ArtifactSetKey::LuckyDog),
            "幸运儿沙漏" => Some(ArtifactSetKey::LuckyDog),
            "幸运儿之杯" => Some(ArtifactSetKey::LuckyDog),
            "幸运儿银冠" => Some(ArtifactSetKey::LuckyDog),
            "游医的银莲" => Some(ArtifactSetKey::TravelingDoctor),
            "游医的枭羽" => Some(ArtifactSetKey::TravelingDoctor),
            "游医的怀钟" => Some(ArtifactSetKey::TravelingDoctor),
            "游医的药壶" => Some(ArtifactSetKey::TravelingDoctor),
            "游医的方巾" => Some(ArtifactSetKey::TravelingDoctor),
            "勋绩之花" => Some(ArtifactSetKey::TenacityOfTheMillelith),
            "昭武翎羽" => Some(ArtifactSetKey::TenacityOfTheMillelith),
            "金铜时晷" => Some(ArtifactSetKey::TenacityOfTheMillelith),
            "盟誓金爵" => Some(ArtifactSetKey::TenacityOfTheMillelith),
            "将帅兜鍪" => Some(ArtifactSetKey::TenacityOfTheMillelith),
            "无垢之花" => Some(ArtifactSetKey::PaleFlame),
            "贤医之羽" => Some(ArtifactSetKey::PaleFlame),
            "停摆之刻" => Some(ArtifactSetKey::PaleFlame),
            "超越之盏" => Some(ArtifactSetKey::PaleFlame),
            "嗤笑之面" => Some(ArtifactSetKey::PaleFlame),
            "明威之镡" => Some(ArtifactSetKey::EmblemOfSeveredFate),
            "切落之羽" => Some(ArtifactSetKey::EmblemOfSeveredFate),
            "雷云之笼" => Some(ArtifactSetKey::EmblemOfSeveredFate),
            "绯花之壶" => Some(ArtifactSetKey::EmblemOfSeveredFate),
            "华饰之兜" => Some(ArtifactSetKey::EmblemOfSeveredFate),
            "羁缠之花" => Some(ArtifactSetKey::ShimenawasReminiscence),
            "思忆之矢" => Some(ArtifactSetKey::ShimenawasReminiscence),
            "朝露之时" => Some(ArtifactSetKey::ShimenawasReminiscence),
            "祈望之心" => Some(ArtifactSetKey::ShimenawasReminiscence),
            "无常之面" => Some(ArtifactSetKey::ShimenawasReminiscence),
            "荣花之期" => Some(ArtifactSetKey::HuskOfOpulentDreams),
            "华馆之羽" => Some(ArtifactSetKey::HuskOfOpulentDreams),
            "众生之谣" => Some(ArtifactSetKey::HuskOfOpulentDreams),
            "梦醒之瓢" => Some(ArtifactSetKey::HuskOfOpulentDreams),
            "形骸之笠" => Some(ArtifactSetKey::HuskOfOpulentDreams),
            "海染之花" => Some(ArtifactSetKey::OceanHuedClam),
            "渊宫之羽" => Some(ArtifactSetKey::OceanHuedClam),
            "离别之贝" => Some(ArtifactSetKey::OceanHuedClam),
            "真珠之笼" => Some(ArtifactSetKey::OceanHuedClam),
            "海祇之冠" => Some(ArtifactSetKey::OceanHuedClam),
            _ => None,
        }
    }
}

impl ArtifactSlotKey {
    pub fn from_zh_cn(s: &str) -> Option<ArtifactSlotKey> {
        // let s = match get_real_artifact_name_chs(s) {
        //     Some(v) => v,
        //     None => return None,
        // };
        match s {
            "磐陀裂生之花" => Some(ArtifactSlotKey::Flower),
            "嵯峨群峰之翼" => Some(ArtifactSlotKey::Plume),
            "星罗圭壁之晷" => Some(ArtifactSlotKey::Sands),
            "星罗圭璧之晷" => Some(ArtifactSlotKey::Sands),
            "巉岩琢塑之樽" => Some(ArtifactSlotKey::Goblet),
            "不动玄石之相" => Some(ArtifactSlotKey::Circlet),
            "历经风雪的思念" => Some(ArtifactSlotKey::Flower),
            "摧冰而行的执望" => Some(ArtifactSlotKey::Plume),
            "冰雪故园的终期" => Some(ArtifactSlotKey::Sands),
            "遍结寒霜的傲骨" => Some(ArtifactSlotKey::Goblet),
            "破冰踏雪的回音" => Some(ArtifactSlotKey::Circlet),
            "染血的铁之心" => Some(ArtifactSlotKey::Flower),
            "染血的黑之羽" => Some(ArtifactSlotKey::Plume),
            "骑士染血之时" => Some(ArtifactSlotKey::Sands),
            "染血骑士之杯" => Some(ArtifactSlotKey::Goblet),
            "染血的铁假面" => Some(ArtifactSlotKey::Circlet),
            "魔女的炎之花" => Some(ArtifactSlotKey::Flower),
            "魔女常燃之羽" => Some(ArtifactSlotKey::Plume),
            "魔女破灭之时" => Some(ArtifactSlotKey::Sands),
            "魔女的心之火" => Some(ArtifactSlotKey::Goblet),
            "焦灼的魔女帽" => Some(ArtifactSlotKey::Circlet),
            "角斗士的留恋" => Some(ArtifactSlotKey::Flower),
            "角斗士的归宿" => Some(ArtifactSlotKey::Plume),
            "角斗士的希冀" => Some(ArtifactSlotKey::Sands),
            "角斗士的酣醉" => Some(ArtifactSlotKey::Goblet),
            "角斗士的凯旋" => Some(ArtifactSlotKey::Circlet),
            "饰金胸花" => Some(ArtifactSlotKey::Flower),
            "追忆之风" => Some(ArtifactSlotKey::Plume),
            "坚铜罗盘" => Some(ArtifactSlotKey::Sands),
            "沉波之盏" => Some(ArtifactSlotKey::Goblet),
            "酒渍船帽" => Some(ArtifactSlotKey::Circlet),
            "渡火者的决绝" => Some(ArtifactSlotKey::Flower),
            "渡火者的解脱" => Some(ArtifactSlotKey::Plume),
            "渡火者的煎熬" => Some(ArtifactSlotKey::Sands),
            "渡火者的醒悟" => Some(ArtifactSlotKey::Goblet),
            "渡火者的智慧" => Some(ArtifactSlotKey::Circlet),
            "远方的少女之心" => Some(ArtifactSlotKey::Flower),
            "少女飘摇的思念" => Some(ArtifactSlotKey::Plume),
            "少女苦短的良辰" => Some(ArtifactSlotKey::Sands),
            "少女片刻的闲暇" => Some(ArtifactSlotKey::Goblet),
            "少女易逝的芳颜" => Some(ArtifactSlotKey::Circlet),
            "宗室之花" => Some(ArtifactSlotKey::Flower),
            "宗室之翎" => Some(ArtifactSlotKey::Plume),
            "宗室时计" => Some(ArtifactSlotKey::Sands),
            "宗室银瓮" => Some(ArtifactSlotKey::Goblet),
            "宗室面具" => Some(ArtifactSlotKey::Circlet),
            "夏祭之花" => Some(ArtifactSlotKey::Flower),
            "夏祭终末" => Some(ArtifactSlotKey::Plume),
            "夏祭之刻" => Some(ArtifactSlotKey::Sands),
            "夏祭水玉" => Some(ArtifactSlotKey::Goblet),
            "夏祭之面" => Some(ArtifactSlotKey::Circlet),
            "平雷之心" => Some(ArtifactSlotKey::Flower),
            "平雷之羽" => Some(ArtifactSlotKey::Plume),
            "平雷之刻" => Some(ArtifactSlotKey::Sands),
            "平雷之器" => Some(ArtifactSlotKey::Goblet),
            "平雷之冠" => Some(ArtifactSlotKey::Circlet),
            "雷鸟的怜悯" => Some(ArtifactSlotKey::Flower),
            "雷灾的孑遗" => Some(ArtifactSlotKey::Plume),
            "雷霆的时计" => Some(ArtifactSlotKey::Sands),
            "降雷的凶兆" => Some(ArtifactSlotKey::Goblet),
            "唤雷的头冠" => Some(ArtifactSlotKey::Circlet),
            "野花记忆的绿野" => Some(ArtifactSlotKey::Flower),
            "猎人青翠的箭羽" => Some(ArtifactSlotKey::Plume),
            "翠绿猎人的笃定" => Some(ArtifactSlotKey::Sands),
            "翠绿猎人的容器" => Some(ArtifactSlotKey::Goblet),
            "翠绿的猎人之冠" => Some(ArtifactSlotKey::Circlet),
            "乐团的晨光" => Some(ArtifactSlotKey::Flower),
            "琴师的箭羽" => Some(ArtifactSlotKey::Plume),
            "终幕的时计" => Some(ArtifactSlotKey::Sands),
            "终末的时计" => Some(ArtifactSlotKey::Sands),
            "吟游者之壶" => Some(ArtifactSlotKey::Goblet),
            "指挥的礼帽" => Some(ArtifactSlotKey::Circlet),
            "战狂的蔷薇" => Some(ArtifactSlotKey::Flower),
            "战狂的翎羽" => Some(ArtifactSlotKey::Plume),
            "战狂的时计" => Some(ArtifactSlotKey::Sands),
            "战狂的骨杯" => Some(ArtifactSlotKey::Goblet),
            "战狂的鬼面" => Some(ArtifactSlotKey::Circlet),
            "勇士的勋章" => Some(ArtifactSlotKey::Flower),
            "勇士的期许" => Some(ArtifactSlotKey::Plume),
            "勇士的坚毅" => Some(ArtifactSlotKey::Sands),
            "勇士的壮行" => Some(ArtifactSlotKey::Goblet),
            "勇士的冠冕" => Some(ArtifactSlotKey::Circlet),
            "守护之花" => Some(ArtifactSlotKey::Flower),
            "守护徽印" => Some(ArtifactSlotKey::Plume),
            "守护座钟" => Some(ArtifactSlotKey::Sands),
            "守护之皿" => Some(ArtifactSlotKey::Goblet),
            "守护束带" => Some(ArtifactSlotKey::Circlet),
            "流放者之花" => Some(ArtifactSlotKey::Flower),
            "流放者之羽" => Some(ArtifactSlotKey::Plume),
            "流放者怀表" => Some(ArtifactSlotKey::Sands),
            "流放者之杯" => Some(ArtifactSlotKey::Goblet),
            "流放者头冠" => Some(ArtifactSlotKey::Circlet),
            "赌徒的胸花" => Some(ArtifactSlotKey::Flower),
            "赌徒的羽饰" => Some(ArtifactSlotKey::Plume),
            "赌徒的怀表" => Some(ArtifactSlotKey::Sands),
            "赌徒的骰盅" => Some(ArtifactSlotKey::Goblet),
            "赌徒的耳环" => Some(ArtifactSlotKey::Circlet),
            "教官的胸花" => Some(ArtifactSlotKey::Flower),
            "教官的羽饰" => Some(ArtifactSlotKey::Plume),
            "教官的怀表" => Some(ArtifactSlotKey::Sands),
            "教官的茶杯" => Some(ArtifactSlotKey::Goblet),
            "教官的帽子" => Some(ArtifactSlotKey::Circlet),
            "武人的红花" => Some(ArtifactSlotKey::Flower),
            "武人的羽饰" => Some(ArtifactSlotKey::Plume),
            "武人的水漏" => Some(ArtifactSlotKey::Sands),
            "武人的酒杯" => Some(ArtifactSlotKey::Goblet),
            "武人的头巾" => Some(ArtifactSlotKey::Circlet),
            "祭水礼冠" => Some(ArtifactSlotKey::Circlet),
            "祭火礼冠" => Some(ArtifactSlotKey::Circlet),
            "祭雷礼冠" => Some(ArtifactSlotKey::Circlet),
            "祭冰礼冠" => Some(ArtifactSlotKey::Circlet),
            "故人之心" => Some(ArtifactSlotKey::Flower),
            "归乡之羽" => Some(ArtifactSlotKey::Plume),
            "逐光之石" => Some(ArtifactSlotKey::Sands),
            "异国之盏" => Some(ArtifactSlotKey::Goblet),
            "感别之冠" => Some(ArtifactSlotKey::Circlet),
            "学士的书签" => Some(ArtifactSlotKey::Flower),
            "学士的羽笔" => Some(ArtifactSlotKey::Plume),
            "学士的时钟" => Some(ArtifactSlotKey::Sands),
            "学士的墨杯" => Some(ArtifactSlotKey::Goblet),
            "学士的镜片" => Some(ArtifactSlotKey::Circlet),
            "奇迹之花" => Some(ArtifactSlotKey::Flower),
            "奇迹之羽" => Some(ArtifactSlotKey::Plume),
            "奇迹之沙" => Some(ArtifactSlotKey::Sands),
            "奇迹之杯" => Some(ArtifactSlotKey::Goblet),
            "奇迹耳坠" => Some(ArtifactSlotKey::Circlet),
            "冒险家之花" => Some(ArtifactSlotKey::Flower),
            "冒险家尾羽" => Some(ArtifactSlotKey::Plume),
            "冒险家怀表" => Some(ArtifactSlotKey::Sands),
            "冒险家金杯" => Some(ArtifactSlotKey::Goblet),
            "冒险家头带" => Some(ArtifactSlotKey::Circlet),
            "幸运儿绿花" => Some(ArtifactSlotKey::Flower),
            "幸运儿鹰羽" => Some(ArtifactSlotKey::Plume),
            "幸运儿沙漏" => Some(ArtifactSlotKey::Sands),
            "幸运儿之杯" => Some(ArtifactSlotKey::Goblet),
            "幸运儿银冠" => Some(ArtifactSlotKey::Circlet),
            "游医的银莲" => Some(ArtifactSlotKey::Flower),
            "游医的枭羽" => Some(ArtifactSlotKey::Plume),
            "游医的怀钟" => Some(ArtifactSlotKey::Sands),
            "游医的药壶" => Some(ArtifactSlotKey::Goblet),
            "游医的方巾" => Some(ArtifactSlotKey::Circlet),
            "勋绩之花" => Some(ArtifactSlotKey::Flower),
            "昭武翎羽" => Some(ArtifactSlotKey::Plume),
            "金铜时晷" => Some(ArtifactSlotKey::Sands),
            "盟誓金爵" => Some(ArtifactSlotKey::Goblet),
            "将帅兜鍪" => Some(ArtifactSlotKey::Circlet),
            "无垢之花" => Some(ArtifactSlotKey::Flower),
            "贤医之羽" => Some(ArtifactSlotKey::Plume),
            "停摆之刻" => Some(ArtifactSlotKey::Sands),
            "超越之盏" => Some(ArtifactSlotKey::Goblet),
            "嗤笑之面" => Some(ArtifactSlotKey::Circlet),
            "明威之镡" => Some(ArtifactSlotKey::Flower),
            "切落之羽" => Some(ArtifactSlotKey::Plume),
            "雷云之笼" => Some(ArtifactSlotKey::Sands),
            "绯花之壶" => Some(ArtifactSlotKey::Goblet),
            "华饰之兜" => Some(ArtifactSlotKey::Circlet),
            "羁缠之花" => Some(ArtifactSlotKey::Flower),
            "思忆之矢" => Some(ArtifactSlotKey::Plume),
            "朝露之时" => Some(ArtifactSlotKey::Sands),
            "祈望之心" => Some(ArtifactSlotKey::Goblet),
            "无常之面" => Some(ArtifactSlotKey::Circlet),
            "荣花之期" => Some(ArtifactSlotKey::Flower),
            "华馆之羽" => Some(ArtifactSlotKey::Plume),
            "众生之谣" => Some(ArtifactSlotKey::Sands),
            "梦醒之瓢" => Some(ArtifactSlotKey::Goblet),
            "形骸之笠" => Some(ArtifactSlotKey::Circlet),
            "海染之花" => Some(ArtifactSlotKey::Flower),
            "渊宫之羽" => Some(ArtifactSlotKey::Plume),
            "离别之贝" => Some(ArtifactSlotKey::Sands),
            "真珠之笼" => Some(ArtifactSlotKey::Goblet),
            "海祇之冠" => Some(ArtifactSlotKey::Circlet),
            _ => None,
        }
    }
}

impl CharacterKey {
    pub fn from_zh_cn(s: &str) -> Option<CharacterKey> {
        match s {
            "阿贝多" => Some(CharacterKey::Albedo),
            "埃洛伊" => Some(CharacterKey::Aloy),
            "安柏" => Some(CharacterKey::Amber),
            "荒泷一斗" => Some(CharacterKey::AratakiItto),
            "芭芭拉" => Some(CharacterKey::Barbara),
            "北斗" => Some(CharacterKey::Beidou),
            "班尼特" => Some(CharacterKey::Bennett),
            "重云" => Some(CharacterKey::Chongyun),
            "迪卢克" => Some(CharacterKey::Diluc),
            "迪奥娜" => Some(CharacterKey::Diona),
            "优菈" => Some(CharacterKey::Eula),
            "菲谢尔" => Some(CharacterKey::Fischl),
            "甘雨" => Some(CharacterKey::Ganyu),
            "五郎" => Some(CharacterKey::Gorou),
            "胡桃" => Some(CharacterKey::HuTao),
            "琴" => Some(CharacterKey::Jean),
            "枫原万叶" => Some(CharacterKey::KaedeharaKazuha),
            "凯亚" => Some(CharacterKey::Kaeya),
            "神里绫华" => Some(CharacterKey::KamisatoAyaka),
            "刻晴" => Some(CharacterKey::Keqing),
            "可莉" => Some(CharacterKey::Klee),
            "早柚" => Some(CharacterKey::KujouSara),
            "丽莎" => Some(CharacterKey::Lisa),
            "莫娜" => Some(CharacterKey::Mona),
            "凝光" => Some(CharacterKey::Ningguang),
            "诺艾尔" => Some(CharacterKey::Noelle),
            "七七" => Some(CharacterKey::Qiqi),
            "雷电将军" => Some(CharacterKey::RaidenShogun),
            "雷泽" => Some(CharacterKey::Razor),
            "罗莎莉亚" => Some(CharacterKey::Rosaria),
            "珊瑚宫心海" => Some(CharacterKey::SangonomiyaKokomi),
            "九条裟罗" => Some(CharacterKey::Sayu),
            "砂糖" => Some(CharacterKey::Sucrose),
            "达达利亚" => Some(CharacterKey::Tartaglia),
            "托马" => Some(CharacterKey::Thoma),
            "旅行者" => Some(CharacterKey::Traveler),
            "温蒂" => Some(CharacterKey::Venti),
            "香菱" => Some(CharacterKey::Xiangling),
            "魈" => Some(CharacterKey::Xiao),
            "行秋" => Some(CharacterKey::Xingqiu),
            "辛焱" => Some(CharacterKey::Xinyan),
            "烟绯" => Some(CharacterKey::Yanfei),
            "宵宫" => Some(CharacterKey::Yoimiya),
            "钟离" => Some(CharacterKey::Zhongli),
            _ => None,
        }
    }
}
