name: CI

on: [push, pull_request, workflow_dispatch]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --release
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: yas.exe
        path: target/release/yas.exe
  Pack:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - name: Download Amenoma
        uses: actions/download-artifact@v2.0.10
        with:
          name: yas.exe
      - name: current directory
        run: ls
      - name: Release
        uses: fnkr/github-action-ghr@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GHR_PATH: yas.exe
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
